import * from "std/text"
import { input_prompt } from "std/env"

echo "Tic Tac Toe by @macioszektv\n"

let table = ["", "", "", "", "", "", "", "", ""]

let is_playing = true
let winner = ""

pub fun move(selected_row: Int, selected_col: Int): Int{
    let table_move = 0

    if{
        selected_row == 1 and selected_col == 1{
            table_move = 0
            return table_move
        }
        selected_row == 1 and selected_col != 1{
            table_move = selected_row*(selected_col-1)
            return table_move
        }
        selected_row == 2{
            table_move = (selected_row-1)*(selected_col-1)+3
            return table_move
        }
        selected_row == 3{
            table_move = (selected_row-2)*(selected_col-1)+6
            return table_move
        }
    }
}

pub fun win_check(){
    if{
        table[0] == "O" and table[1] == "O" and table[2] == "O" {
            is_playing = false
            winner = "Player One"
        }
        table[3] == "O" and table[4] == "O" and table[5] == "O" {
            is_playing = false
            winner = "Player One"
        }
        table[6] == "O" and table[7] == "O" and table[8] == "O" {
            is_playing = false
            winner = "Player One"
        }
        table[0] == "O" and table[3] == "O" and table[5] == "O" {
            is_playing = false
            winner = "Player One"
        }
        table[1] == "O" and table[4] == "O" and table[7] == "O" {
            is_playing = false
            winner = "Player One"
        }
        table[2] == "O" and table[5] == "O" and table[8] == "O"{
            is_playing = false
            winner = "Player One"
        }
        table[0] == "O" and table[4] == "O" and table[8] == "O" {
            is_playing = false
            winner = "Player One"
        }
        table[2] == "O" and table[4] == "O" and table[6] == "O" {
            is_playing = false
            winner = "Player One"
        }
        table[0] == "X" and table[1] == "X" and table[2] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[0] == "X" and table[1] == "X" and table[2] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[3] == "X" and table[4] == "X" and table[5] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[6] == "X" and table[7] == "X" and table[8] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[0] == "X" and table[3] == "X" and table[5] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[1] == "X" and table[4] == "X" and table[7] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[2] == "X" and table[5] == "X" and table[8] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[0] == "X" and table[4] == "X" and table[8] == "X" {
            is_playing = false
            winner = "Player Two"
        }
        table[2] == "X" and table[4] == "X" and table[6] == "X" {
            is_playing = false
            winner = "Player Two"
        }
    }
}

pub fun print_table() {
    echo "-----------"
    echo "| {table[0]} | {table[1]} | {table[2]} |"
    echo "-----------"
    echo "| {table[3]} | {table[4]} | {table[5]} |"
    echo "-----------"
    echo "| {table[6]} | {table[7]} | {table[8]} |"
    echo "-----------"

    win_check()
}

pub fun game(){
    echo "\nPlayer 1 move:\n"

    const selected_row = parse_int(input_prompt("Select a row (1, 2, 3): ")) failed {
        echo "Invalid input. Please enter a number between 1 and 3."
        exit(1)
    }
    const selected_col = parse_int(input_prompt("Select a column (1, 2, 3): ")) failed {
        echo "Invalid input. Please enter a number between 1 and 3."
        exit(1)
    }

    const table_move = move(selected_row, selected_col)
        
    table[table_move] = "O"

    print_table()

    if is_playing == true{
        echo "\nPlayer 2 move:\n"

        const selected_row_2 = parse_int(input_prompt("Select a row (1, 2, 3): ")) failed {
            echo "Invalid input. Please enter a number between 1 and 3."
            exit(1)
        }
        const selected_col_2 = parse_int(input_prompt("Select a column (1, 2, 3): ")) failed {
            echo "Invalid input. Please enter a number between 1 and 3."
            exit(1)
        }

        const table_move = move(selected_row_2, selected_col_2)

        table[table_move] = "X"

        print_table()
    }
}

loop{
    if is_playing == false{
        echo "\n\nGame over!"
        echo "Winner is {winner}"
        break
    }else{
        game()
    } 
}